server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${local.datasource.url}
    username: ${local.datasource.username}
    password: ${local.datasource.password}
  jpa:
#    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${local.redis.host}
      port: ${local.redis.port}
      timeout: 10
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${local.oauth2.google.client-id}
                client-secret: ${local.oauth2.google.client-secret}
                scope: ${local.oauth2.google.scope}


springdoc:
  api-docs:
    groups:
      enabled: true
#    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC


